Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 36, in handle_read
    print('test {}'.format(self.socket.raddr))
AttributeError: 'socket' object has no attribute 'raddr'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 45, in handle_read
    self.send(_api_request_handler.handle(method, headers, post_data))
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 60, in handle
    return self.getResponse(isRequestHttp, (json.dumps(response) + '\n').encode('utf-8'))
AttributeError: 'ApiRequestHandler' object has no attribute 'getResponse'
Error during parsing request. 
Client: ('127.0.0.1', 34652) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 0'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 34656) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 0'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 34690) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'Content-Type': ' application/x-www-form-urlencoded', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 3'}, '1=2\n') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 34706) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'Content-Type': ' application/json', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 8'}, '{"1": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 25, in parse
    if len(request[key]) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 34712) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'Content-Type': ' application/json', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 8'}, '{"1": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 25, in parse
    if len(request[key]) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 34728) 
Request: ('post', {'Host': ' localhost:55555', 'Connection': ' keep-alive', 'Accept': ' */*', 'Content-Type': ' application/json', 'User-Agent': ' python-requests/2.18.4', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 8'}, '{"1": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 25, in parse
    if len(request[key]) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error during parsing request. 
Client: ('127.0.0.1', 35084) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 8', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"1": 2}\n') 
Exception: Key '1' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 35144) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 9', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"a1": 2}\n') 
Exception: Key 'a1' isn't allowed
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 35164) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 12', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"model": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 24, in parse
    self._validate_key_value(key, request[key])
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 34, in _validate_key_value
    if len(value) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 35174) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 12', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"model": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 24, in parse
    self._validate_key_value(key, request[key])
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 34, in _validate_key_value
    if len(value) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 35184) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 12', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"model": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 24, in parse
    self._validate_key_value(key, request[key])
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 34, in _validate_key_value
    if len(value) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 35188) 
Request: ('post', {'Content-Type': ' application/json', 'Accept': ' */*', 'Content-Length': ' 12', 'Accept-Encoding': ' gzip, deflate', 'Host': ' localhost:55555', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4'}, '{"model": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 24, in parse
    self._validate_key_value(key, request[key])
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 34, in _validate_key_value
    if len(value) > self.MAXIMUM_VALUE_LENGTH:
TypeError: object of type 'int' has no len()
Error in ApiRequestHandler. 
Client: ('127.0.0.1', 35664) 
Request: ('post', {'Accept': ' */*', 'Connection': ' keep-alive', 'User-Agent': ' python-requests/2.18.4', 'Content-Type': ' application/json', 'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 12', 'Host': ' localhost:55555'}, '{"model": 2}\n')
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/api_request_handler.py", line 30, in handle
    reqDict = self.requestParser.parse(json_data)
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 24, in parse
    self._validate_key_value(key, request[key])
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 45, in _validate_key_value
    self._validate_value_regex(key, value, r'^[a-zA-Z][a-zA-Z0-9_]+$')
  File "/home/user/python-projects/proxy_py/server/requests_to_models/request_parser.py", line 58, in _validate_value_regex
    if not re.match(pattern, value):
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
Error during parsing request. 
Client: ('127.0.0.1', 36502) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 12', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"model": 2}\n') 
Exception: Value of key 'model' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 36532) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 13', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"model": []}\n') 
Exception: Value of key 'model' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 36592) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 14', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"fields": []}\n') 
Exception: Value of key 'fields' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 36604) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 20', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"fields": ["dsaf"]}\n') 
Exception: Value of key 'fields' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 36620) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 18', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"fields": "dsaf"}\n') 
Exception: You should specify 'model'
Error during parsing request. 
Client: ('127.0.0.1', 36672) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 17', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"model": "test"}\n') 
Exception: Model doesn't exist or isn't allowed
Error during parsing request. 
Client: ('127.0.0.1', 36678) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 18', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' python-requests/2.18.4', 'Connection': ' keep-alive'}, '{"model": "proxy"}\n') 
Exception: You should specify 'method'
Error during parsing request. 
Client: ('127.0.0.1', 37068) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/octet-stream', 'Content-Length': ' 0', 'Accept': ' */*', 'Host': ' localhost:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 37602) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/octet-stream', 'Content-Length': ' 0', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 37614) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/octet-stream', 'Content-Length': ' 0', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 37710) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 18', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '{"model": "proxy"}\n') 
Exception: You should specify 'method'
Error during parsing request. 
Client: ('127.0.0.1', 37778) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 36', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '{"method": "gets", "model": "proxy"}\n') 
Exception: Method doesn't exist or isn't allowed
Error during parsing request. 
Client: ('127.0.0.1', 37804) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 37', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '{"model": "proxy", "method": "gets\'"}\n') 
Exception: Value of key 'method' doesn't match to pattern ^[a-zA-Z][a-zA-Z0-9_]+$
Error during parsing request. 
Client: ('127.0.0.1', 37816) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Type': ' application/json', 'Content-Length': ' 36', 'Accept': ' */*', 'Host': ' 127.0.0.1:55555', 'User-Agent': ' Python/3.5 aiohttp/2.3.1'}, '{"method": "gets", "model": "proxy"}\n') 
Exception: Method doesn't exist or isn't allowed
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 44, in handle_read
    method, url, headers, post_data = parse_http(data.decode('utf-8'))
ValueError: not enough values to unpack (expected 4, got 3)
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 44, in handle_read
    method, url, headers, post_data = parse_http(data.decode('utf-8'))
ValueError: not enough values to unpack (expected 4, got 3)
Error in RequestHandler
Traceback (most recent call last):
  File "/home/user/python-projects/proxy_py/server/proxy_provider_server.py", line 44, in handle_read
    method, url, headers, post_data = parse_http(data.decode('utf-8'))
ValueError: not enough values to unpack (expected 4, got 3)
Error during parsing request. 
Client: ('127.0.0.1', 40260) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 0', 'Host': ' localhost:55555', 'Accept': ' */*', 'User-Agent': ' HTTPie/0.9.2', 'Connection': ' keep-alive'}, '') 
Exception: Your request doesn't look like json. Maybe it's not json?
Error during parsing request. 
Client: ('127.0.0.1', 40300) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 13', 'Content-Type': ' application/json', 'Host': ' localhost:55555', 'Accept': ' application/json', 'User-Agent': ' HTTPie/0.9.2', 'Connection': ' keep-alive'}, '{"test": "1"}\n') 
Exception: Key 'test' isn't allowed
Error during parsing request. 
Client: ('127.0.0.1', 40320) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 18', 'Content-Type': ' application/json', 'Host': ' localhost:55555', 'Accept': ' application/json', 'User-Agent': ' HTTPie/0.9.2', 'Connection': ' keep-alive'}, '{"model": "proxy"}\n') 
Exception: You should specify 'method'
Error during parsing request. 
Client: ('127.0.0.1', 40360) 
Request: ('post', {'Accept-Encoding': ' gzip, deflate', 'Content-Length': ' 18', 'Content-Type': ' application/json', 'Host': ' localhost:55555', 'Accept': ' application/json', 'User-Agent': ' HTTPie/0.9.2', 'Connection': ' keep-alive'}, '{"model": "proxy"}\n') 
Exception: You should specify 'method'
